import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./Footer";
import Navbar from "./Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Rashed Alfoqha",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" bg-slate-50">
        <Navbar />
        {children}
       <Footer />
      </body>
    </html>
  );
}
